name: Terraform Format Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terraform_fmt:
    name: Check Terraform Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.x

      - name: Run terraform fmt check
        id: fmt
        run: terraform fmt -check -recursive
        # If terraform fmt finds unformatted files, it will exit with a non-zero code, failing the job.
